[tool.poetry]
name = "part1"
version = "0.1.0"
description = ""
authors = ["Daniel Ranchal <danielranchal@correo.ugr.es>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
